
export const metadata = {
  title: 'ChatGPT',
  description: 'Generated by Next.js',
}
import '../src/styles/globals.css';
import { SessionProvider } from './components/SessionProvider';
import Sidebar from './components/Sidebar';
import { getServerSession } from 'next-auth';
import Login from './components/Login';
import { authOptions } from '/Users/bhubeshsr/Desktop/Bhubesh/chatgpt-clone/src/pages/api/auth/[...nextauth].ts';
import ClientProvider from './components/ClientProvider';

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      
      <body>
        <SessionProvider session={session}>

          {!session ? (
              <Login></Login>
          ): (
            <div className="flex">
          {/* side bar */}
          <div className='bg-[#202123] max-w-xs h-screen overflow-y-scroll md:min-w-[20rem]'>
          <Sidebar></Sidebar>
          </div>
          
          {/* client provider  for notifications */}
           <ClientProvider></ClientProvider>
          <div className="bg-[#343541] flex-1">
          {children}
          </div>
        </div>
          )}
        </SessionProvider>
        </body>
    </html>
  )
}


